### ISSUE TITLE
Do you use validation data for training when report results on test split

### ISSUE THREAD

**Issue by yaoqi-zd** [jiwoon-ahn/psa#15]
suppose the augmented VOC dataset can be splited into train_aug(10582)+val(1449)+test(1456),
when you report results on test split in your paper, do you use train_aug + val for training or just use train_aug?
thx!

**Comment by jiwoon-ahn** [comment]
Hi @yaoqi-zd,
Some works (e.g. DeepLab) did use (train_aug + val) for training and this could get us slightly better results, but we decided not to.

**Comment by yaoqi-zd** [comment]
THX!
