### ISSUE TITLE
Can you share your training command for ResNet-38 segmentation network?

### ISSUE THREAD

**Issue by rulixiang** [jiwoon-ahn/psa#26]
Hi, thanks for your brilliant work! 
When I tried to reproduce the ResNet38 segmentation network, I found the repo you mentioned (https://github.com/jiwoon-ahn/psa/issues/7#issuecomment-430170981_) didn't give the training command. So I'm wondering if you can share your training command for ResNet-38 segmentation network?

**Comment by jemmooo** [comment]
@rulixiang what was the training command that you ended up using?
